# Site Settings
#=include site.yml

# Social Media Settings
# Remove the item if you don't need it
#=include social.yml

# Posts Settings
#=include posts.yml

# Advanced Settings
#=include advanced.yml

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Kramdown 설정
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md',
  'assets/css/preview.scss'
]

# Theme
version: v3.1.0
