name: PYY0715's Research Blog For Data Science
title: PYY0715 | Research Blog
# description: Jekflix is a template for Jekyll inspired by Netflix and made by
#   Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: pushpyy@gmail.com
disqus_username: pyy0715
